Adding  twin normative modelling project
school-brainhack/school-brainhack.github.io pull request #150
Opened 2022-10-10 07:57 UTC by likeajumprope

Pull request to add twin normative modelling project to the website. 
Related to issue #149

2023-06-09 17:31 UTC, FrancoisPgm requested changes
The title and cover image were not properly set but other than that it's great.

2023-06-09 17:31 UTC, FrancoisPgm commented on content/en/project/Twin-normative-modelling/index.md
> +title: "This is an example project page which serves as a template"
```suggestion
title: "Twin normative modelling project"
```
put your project title here

2023-06-09 17:31 UTC, FrancoisPgm commented on content/en/project/Twin-normative-modelling/index.md
> +<img src="images/normative.png" width="400">
```suggestion
image: "images/normative.png"
```

2023-06-12 01:59 UTC, likeajumprope commented
I have committed the suggested changes - what else needs to be done so that the PR can be merged? :)

2023-06-12 16:30 UTC, merged

2023-06-12 16:31 UTC, pbellec commented
Looks great @likeajumprope sorry about the delay! 

Your project is going to be incorporated in the 2023 gallery, because we took so long to merge it.