added project index.md and images
school-brainhack/school-brainhack.github.io pull request #253
Opened 2023-06-05 15:13 UTC by louisfb01

This is a pull request to add [my BrainHack project](https://github.com/brainhack-school2023/bouchard_project) to the gallery, following https://school.brainhackmtl.org/project_guide/.

2023-06-08 18:54 UTC, louisfb01 commented
@valosekj

2023-06-08 20:41 UTC, valosekj commented
> Tagging TA @valosekj for review :)

Nice! I have a vacation from 9-17 June --> will review it after.

2023-06-13 13:17 UTC, pbellec requested changes
I've rendered the page, and everything looks great. Congrats on the awesome project. Pending the minor comment I'll left, I'll be ready to merge. I'll wait a bit on the review by the Poly hub though.

2023-06-13 13:17 UTC, pbellec commented on content/en/project/general-spinal-cord-segmentation/index.md
> +* A Github repository with codes and scripts to reproduce training and testing `github.com/brainhack-school2023/bouchard_project`.
```suggestion
* A [Github repository](https://github.com/brainhack-school2023/bouchard_project) with codes and scripts to reproduce training and testing.
```

2023-06-13 13:17 UTC, pbellec commented on content/en/project/general-spinal-cord-segmentation/index.md
> +* A Github repository with codes and scripts to reproduce training and testing `github.com/brainhack-school2023/bouchard_project`.
There are several references to docs throughout the report which would be better formatted as links. If you want to have the links in plain text as well, you can make links like [github.com/bla](https://github.com/bla]. These will be rendered in the same style as what you used, but they will be clickable.

2024-05-18 18:30 UTC, pbellec approved these changes

2024-05-18 18:30 UTC, pbellec commented
The review was never properly completed but the report looks good, so I am merging.

2024-05-18 18:30 UTC, merged

2024-05-18 19:12 UTC, valosekj commented
Apologies for no review from my side; it somehow slipped through the cracks.

Indeed, the project looks good. Thanks for merging!