added index.md and three png files
school-brainhack/school-brainhack.github.io pull request #273
Opened 2023-06-11 07:00 UTC by amandalin047

Closes # .

Changes proposed in this pull request:

-
-

2023-06-12 15:45 UTC, pbellec commented
The project is looking good, but it is missing all the meta data.

Please add the header for the document, adapting from the project template: https://raw.githubusercontent.com/school-brainhack/school-brainhack.github.io/main/content/en/project/template/index.md 

Also please add a cover image for your project, which you can link with the `image` field in the header.

2023-06-12 16:07 UTC, pbellec requested changes

2023-06-22 20:31 UTC, amandalin047 commented on content/en/project/RegressionModellingERPs/index.md
> +# Regression-Modelling ERPs (and More!)
Hi @pbellec Sorry for the late reply. I've added the meatadat as is suggested above. Please let me know if any revisions are needed. Many many thanks!

2024-05-18 18:07 UTC, pbellec commented
So sorry this took SOOO long :( LGTM, merging.

2024-05-18 18:08 UTC, pbellec approved these changes

2024-05-18 18:08 UTC, merged