Upload a page for project
school-brainhack/school-brainhack.github.io pull request #276
Opened 2023-06-11 10:47 UTC by dylanscottlow

Closes # .

Note this is a co-authored project.

Authors: Dylan Scott Low Y.J. and Stephanie Fu Pei-Yun

2023-06-12 15:53 UTC, pbellec requested changes
Awesome project! 

There's only a small issue in the header for the project to render properly.

I've suggested the changes (removing two lines). 

Please accept the changes and I'll merge the project.

2023-06-12 15:53 UTC, pbellec commented on content/en/project/duolingo_eeg_ml_classification/index.md
> +
```suggestion
```

2023-06-13 04:39 UTC, dylanscottlow commented
Hi Prof. Bellec,

I've committed the changes you requested. Please let me know if there is anything else needed!

2024-05-18 18:06 UTC, pbellec commented
OMG so sorry I missed merging this :( LGTM merging now.

2024-05-18 18:06 UTC, pbellec approved these changes

2024-05-18 18:06 UTC, merged