added my project
school-brainhack/school-brainhack.github.io pull request #335
Opened 2024-06-21 16:03 UTC by IangolaAndri

Added my project

2024-06-21 18:57 UTC, pbellec requested changes
Thanks so much for submitting your report, it looks great!

But it does look like you added a folder by mistake in content/en/project/tulpa/template. Could you please remove this folder?

2024-06-21 19:51 UTC, IangolaAndri reviewed
Remove the extra folder

2024-06-26 14:36 UTC, pbellec commented
LGTM! Merging.

2024-06-26 14:36 UTC, pbellec approved these changes

2024-06-26 14:36 UTC, merged